version: "3.8"

services: 
    bonsqldb:
        image: postgres:9.6.23
        container_name: bonsqldb
        volumes: 
            - bonvolume2:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${SQL_ROOT_PASSWORD:-unsecured_password}
        ports:
            - 5432:5432
        cap_add:
        - SYS_NICE  # CAP_SYS_NICE (gives sql cpu priority)

    rest-server:
        build: 
            context: .
        container_name: rest-server
        environment: 
            DB_PASS: ${SQL_ROOT_PASSWORD:-unsecured_password}
            ADMIN_PASS: ${ADMIN_PASS:-password123}
            DOCKER_FLAG: 1
            PYTHONUNBUFFERED: 1
        ports:
            - 5000:5000
        volumes:
            - ./:/app

volumes:
    bonvolume2:
        name: bonvolume2

networks: 
    default:
        name: bonback
        driver: bridge